// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using UIKit;

namespace ami.ViewControllers
{
    public partial class HelpViewController : UIViewController
    {
        public HelpViewController(IntPtr handle) : base(handle)
        {
        }

        partial void EmailSupportTouched(NSObject sender)
        {
            UIApplication.SharedApplication.OpenUrl(new NSUrl("mailto:info@ami4kidz.com"));
        }

        partial void CallSupportTouched(NSObject sender)
        {
            UIApplication.SharedApplication.OpenUrl(new NSUrl("tel:1-646-683-4352"));
        }

        partial void WebsiteVisitTouched(NSObject sender)
        {
            UIApplication.SharedApplication.OpenUrl(new NSUrl("http://www.ami4kidz.com"));
        }

        partial void SwichLanguageTouched(NSObject sender)
        {
            var lang = (NSBundle.MainBundle.PreferredLocalizations[0] == "en") ? "zh" : "en";
            var key = new NSString("AppleLanguages");
            string[] languageValues = { lang };
            NSUserDefaults.StandardUserDefaults.SetValueForKey(NSArray.FromObjects(languageValues), key);
            var alert = UIAlertController.Create("Restart", NSBundle.MainBundle.GetLocalizedString("语言转换成功，请彻底关闭然后重启Ami APP，或者重启手机，谢谢"),
                    UIAlertControllerStyle.Alert);
            alert.AddAction(UIAlertAction.Create("Ok", UIAlertActionStyle.Cancel, null));
            PresentViewController(alert, true, null);
        }
    }
}