// This file has been autogenerated from a class added in the UI designer.

using System;
using ami.Model;
using Foundation;
using UIKit;

namespace ami.ViewControllers
{
    public partial class NewReminderChildViewController : UITableViewController
    {
        private VoiceCommandPickerModel _pickerModel;

        public NewReminderChildViewController(IntPtr handle) : base(handle)
        {
        }

        public ReminderModel Reminder => new ReminderModel
        {
            AlarmDate = new DateTimeOffset(TimePicker.Date.ToDateTime().ToUniversalTime()),
            Command = _pickerModel.SelectedItem,
            Name = _pickerModel.SelectedItem.Name,
            RequestId = Guid.NewGuid().ToString()
        };

        public override void ViewDidLoad()
        {
            _pickerModel = new VoiceCommandPickerModel();
            TimePicker.MinimumDate = NSDate.FromTimeIntervalSinceNow(60);
            ChoicePicker.Model = _pickerModel;
            CommandCell.DetailTextLabel.Text = _pickerModel.SelectedItem.Name;
            TimePicker.ValueChanged += (sender, e) =>
            {
                TimeCell.DetailTextLabel.Text = TimePicker.Date.ToDateTime().ToString("g");
            };
            _pickerModel.ValueChanged += (sender, e) =>
            {
                CommandCell.DetailTextLabel.Text = _pickerModel.SelectedItem.Name;
            };
        }
    }
}